name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  
  versions:
    name: View all tools maybe used
    runs-on: ubuntu-latest
    steps:
      - name: show value of environment
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: echo "$DEPLOY_KEY"
      - name: show docker version
        run: |
          docker version &&
          docker info
      - name: show gzip version
        run: gzip --version
      - name: show os version
        run: cat /etc/os-release
      - name: show scp location
        run: which scp
      - name: show ssh location
        run: which ssh
      - name: show ssh-add location
        run: which ssh-add
      - name: show ssh-agent location
        run: which ssh-agent
      - name: show amount of CPU(s)
        run: nproc
      - name: show available RAM
        run: free
