name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  
  versions:
    name: View all tools maybe used
    runs-on: ubuntu-latest
    steps:
      - name: show value of environment
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: echo "$DEPLOY_KEY"
      - name: show docker version
        run: docker version
      - name: show gzip version
        run: gzip --version
      - name: show os version
        run: cat /etc/os-release
      - name: show scp version
        run: scp --version
      - name: show ssh version
        run: ssh --version
