name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
  
  versions:
    name: View all tools maybe used
    runs-on: ubuntu-latest
    steps:
      - name: --version
        run: |
          cat /etc/os-release
          docker --version
          ssh --version
          sch --version
